play:
  iterations: 1 # 10000
  games_per_iteration: 1 # 25000
  mcts_per_move: 800
  resign_false_positive_check: 0.1
  dirichlet_alpha: 0.3
train:
  training_loops: 1000
  batch_size: 2048
  learning_rate:
    - 0.02
    - 0.002
    - 0.0002
